apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-site
  template:
    metadata:
      labels:
        app: html-site
    spec:
      containers:
      - name: nginx
        image: ghcr.io/samundra0/html-site:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-site-service
spec:
  selector:
    app: html-site
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional: specify or let Kubernetes assign one
  type: NodePort

