name: Build & Deploy HTML Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/html-site:latest .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/html-site:latest

    - name: Configure kubectl manually
      run: |
        kubectl config set-cluster jelastic --server=${{ secrets.K8S_API_URL }} --insecure-skip-tls-verify=true
        kubectl config set-context jelastic --cluster=jelastic
        kubectl config set-credentials user --token=${{ secrets.K8S_TOKEN }}
        kubectl config set-context jelastic --user=user
        kubectl config use-context jelastic

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
